name: Feature Request 📜

description: Request for adding a new feature to the project.

body:
  - type: markdown
    attributes:
      value: |
        **Please ensure that all sections are filled out properly to help us evaluate the feature request effectively.**

  - type: checkboxes
    id: terms
    attributes:
      label: 'Important Points to Note'
      options:
        - label: "I agree to adhere to the project's Code of Conduct."
          required: true
        - label: "I have reviewed and understood the project's Contributing Guidelines."
          required: true
        - label: 'I have checked the existing issues and can confirm that this is not a duplicate.'
          required: true
        - label: "I have reviewed and understood the project's Issue Creation Guidelines."
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 'Feature Description'
      placeholder: 'Provide a detailed description of the feature, including its objectives and expected behaviour.'
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots'
      placeholder: 'Copy the image and just paste it to upload on github'
    validations:
      required: true

  - type: input
    id: tech-stacks
    attributes:
      label: 'Tech Stacks'
      description: 'List the technologies used in the feature (comma-separated and in lowercase).'
      placeholder: 'e.g., redis, kafka, etc.'

  - type: dropdown
    id: priority
    attributes:
      label: 'Priority'
      description: 'How much time should be allocated to this issue?'
      options:
        - 'Up to 2 days'
        - 'Up to 5 days'
        - 'Up to 1 week'
    validations:
      required: true

  - type: dropdown
    id: open-source-program
    attributes:
      label: 'Open Source Program'
      description: 'Which open-source program are you participating in?'
      options:
        - 'Hacktoberfest'
        - 'OnlyDust Waves'
        - '24 Pull Requests'
        - 'GSSoC'
        - 'SSOC'
        - 'SWOC'
        - 'JWOC'
        - 'IWOC'
        - 'KWOC'
        - 'DWOC'
        - 'VSOC'
        - 'Others'

  - type: dropdown
    id: on-work
    attributes:
      label: 'Would you like to work on this issue?'
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Difficulty labels (e.g., Easy/Beginner) will be applied once the PR is created.**
        **Do not raise a PR without being assigned to the issue.**
        > **NOTE:** This issue will automatically be unassigned if the PR is not raised within the given time frame.

        #### Happy Coding! 🎉
        All the best with your contribution! 🚀
